[package]
name = "verco"
version = "5.5.2"
authors = ["Matheus Lessa <vamolessa@mm.st>"]
edition = "2018"
exclude = [
    "images/*",
]
description = "A simple Git/Hg version control client based on keyboard shortcuts"
license = "MIT"

documentation = "https://github.com/vamolessa/verco"
homepage = "https://vamolessa.github.com/verco"
repository = "https://github.com/vamolessa/verco"
readme = "README.md"
keywords = ["version-control", "tool", "git", "hg", "cli"]
categories = ["command-line-utilities"]

[[bin]]
name = "verco"
path = "src/main.rs"

[dependencies]
crossterm = "0.17.5"
ctrlc = "3.1.4"
rustyline = "6.1.1"