[package]
name = "verco"
version = "5.0.0"
authors = ["Matheus Lessa <matheuslessarodrigues@gmail.com>"]
edition = "2018"
exclude = [
    "images/*",
]
description = "A simple Git/Hg version control client based on keyboard shortcuts"
license = "MIT"

documentation = "https://github.com/matheuslessarodrigues/verco"
homepage = "https://github.com/matheuslessarodrigues/verco"
repository = "https://github.com/matheuslessarodrigues/verco"
readme = "README.md"
keywords = ["version-control", "tool", "git", "hg", "cli"]
categories = ["command-line-utilities"]

[[bin]]
name = "verco"
path = "src/main.rs"

[dependencies]
directories = "2.0.2"
crossterm = "0.17.1"
ctrlc = "3.1.4"
rustyline = "6.1.1"
toml = "0.5.6"
serde = { version = "1.0", features = ["derive"] }
